### ISSUE TITLE
ScrollTrigger with Locomotive?

### ISSUE THREAD

**Issue by sananes** [ivodolenc/nuxt-locomotive#1]
Hey buddy,

Honestly, fantastic work on all this! Quick question, is there anyway to use ScrollTrigger alongside Locomotive scroll? I tried setting it up this way:

```
this.$gsap.to('[data-project-card]', {
        y: -50,
        opacity: 1,
        ease: 'easeInOut',
        stagger: 0.1,
        scrollTrigger: {
          trigger: '[data-project-overview]',
          scroller: '[data-scroll-container]',
          pin: true,
          end: 'bottom',
          scrub: true
        }
      })
 ```
      
 But unfortunately, no luck.

All the best!

**Comment by ivodolenc** [comment]
Hi, here is [ScrollTrigger.scrollerProxy()](https://greensock.com/docs/v3/Plugins/ScrollTrigger/static.scrollerProxy) docs and [Locomotive Scroll + ScrollTrigger](https://codepen.io/GreenSock/pen/zYrELYe) example. 

Just follow the example, it is very easy to understand.

**Comment by sananes** [comment]
Hey @ivodolenc I'm having a real hard time getting past this bug I'm facing. I've managed to set everything up the way the docs have explained.

I'm running into a problem where the ScrollTrigger and locomotive combination on `smooth: true` causes some very strange issues. When I'm in dev mode on chrome, every time I resize my browser the locomotive kicks in and calculates its height. If load the page when the section I want to animate on ScrollTrigger is out of bounds within my viewport, it doesn't trigger or recognize the locomotive scroll. The minute I change to  `smooth: false`, everything works as expected. Just wanted to know if you managed to get this working nicely on your end and if you've ever encountered this before?
